name: Build & Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-jdk
      - uses: ./.github/actions/gradle-cache

      - name: Run spotlessCheck
        run: ./gradlew spotlessCheck

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-jdk
      - uses: ./.github/actions/gradle-cache

      - name: Run tests
        run: ./gradlew test --stacktrace

  package:
    name: Package Distributions
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-jdk
      - uses: ./.github/actions/gradle-cache

      - name: Build installers
        run: ./gradlew :app:packageDistributionForCurrentOS --stacktrace
